/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIDigitRecog */

#ifndef _Included_JNIDigitRecog
#define _Included_JNIDigitRecog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIDigitRecog
 * Method:    predict
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JNIDigitRecog_predict
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
